### ISSUE TITLE
Hardcoded config.sprite_path option

### ISSUE THREAD

**Issue by Tristam3000** [varvet/middleman-scavenger#1]
Attempting to change the sprite output path in the config file like so...

```
activate :middleman_scavenger do |config|
  config.path = "./source/media/svg"
  config.prefix = "icon-"
  config.sprite_path = "./source/media/svg/svg-defs.svg"
end
```

Returns the following error:

```
/Library/Ruby/Gems/2.0.0/gems/middleman-scavenger-1.0.0/lib/svg_processor.rb:18:in `write': No such file or directory - ./source/images/./source/media/svg/svg-defs.svg (Errno::ENOENT)
```

It feels like the option ought to behave in the same way as the `config.path` option.
I'm using `config.sprite_path = "../media/img/svg-defs.svg` as a quick fix for now

The sprite path looks like it's hardcoded here:
https://github.com/varvet/middleman-scavenger/blob/84d61f0687c7b65fa05974f42fde7ae75557c2e6/lib/svg_processor.rb#L18

**Comment by johanhalse** [comment]
You're quite correct! I've issued a fix (https://github.com/varvet/middleman-scavenger/pull/2) and drafted a [new release](https://github.com/varvet/middleman-scavenger/releases/tag/v1.0.1) that should take care of your issue. Thanks for reporting it!

**Comment by Tristam3000** [comment]
Nice one! Very excited about adding this extension into our Middleman setup
