### ISSUE TITLE
SVG helper options can't be empty

### ISSUE THREAD

**Issue by tlindsay** [varvet/middleman-scavenger#12]
According to IRB:

```
irb(main):001:0> options=nil
nil
irb(main):002:0> defined?(options)
"local-variable"
```

This means that the conditional in the `svg` helper, defined in `lib/middleman-scavenger.rb`, line 46 will always resolve to true. This in turn causes a fatal `undefined method 'map' for nil:nilClass` if no options (such as `class:`) are passed into the helper.

**Comment by johanhalse** [comment]
Fixed in latest release. Thanks!
