### ISSUE TITLE
Async sprite loading fails

### ISSUE THREAD

**Issue by tlindsay** [varvet/middleman-scavenger#14]
I haven't been able to figure out why yet, but `images/sprite.svg` is always a 404 for me. Inlining the spritesheet works like a charm, though.

I've set up the most barebones Middleman install I can in order to make sure I wasn't doing something wrong. [You can check it out here.](https://github.com/tlindsay/middleman-scavenger-test)

Oh, and I don't know what the expected behavior is, but I noticed that there's no `images/sprite.svg` if I `middleman build` either.

**Comment by johanhalse** [comment]
Yes.

There's been a bunch of breaking changes to middleman-core and the gem constraints were set a little too optimistically for our own good. There are some nasty differences between middleman 3.3.x and 3.4.x and I think the easiest way to resolve them is to just require 3.4.x. If anyone wants to use an earlier version, they can just downgrade middleman-scavenger to an earlier version. I have a fix in the works and will add this to the docs.

**Comment by tlindsay** [comment]
I'm not sure if I'm understanding you right, but I don't think that 3.4.x is my problem. [I'm running on 3.4.1 for that test site.](https://github.com/tlindsay/middleman-scavenger-test/blob/master/Gemfile#L5)

Please let me know if there's anything I can do to contribute!

**Comment by johanhalse** [comment]
Fixed in v1.0.4
