### ISSUE TITLE
Generated symbols contain no path information

### ISSUE THREAD

**Issue by Tristam3000** [varvet/middleman-scavenger#4]
The generated SVG file  contains the expected symbols, with the correct ID's, but the symbols contain no path information.
Example generated file:

```
<svg xmlns="http://www.w3.org/2000/svg">
  <symbol viewBox="0 0 50 50" id="icon-facebook"></symbol>
  <symbol viewBox="0 0 50 50" id="icon-mail"></symbol>
  <symbol viewBox="0 0 50 50" id="icon-twitter"></symbol>
</svg>
```

No error message is shown.
I tested this on a 'clean' Middleman project and still ran into the same problem, so doesn't seem to be down to any custom setup issues.

**Comment by johanhalse** [comment]
This is likely an xpath issue. SVG is a little less structured than HTML, you're never really certain where the actual body content begins. Can you link the svg as a gist? I'll take a look at it as soon as I'm home from vacation - or maybe @kindell could check it out earlier.

—

**Comment by Tristam3000** [comment]
No problem, here's a gist with the input file and the generated SVG
https://gist.github.com/Tristam3000/4501214cb135251bd66b

**Comment by kindell** [comment]
Looks like we currently only support `<g>`wrapped SVG content. Have a look at #5 and see if it works out for you, @Tristam3000

**Comment by Tristam3000** [comment]
I gave it a go locally, it's working nicely :)

**Comment by kindell** [comment]
Nice. I will prepare a new release tomorrow!
